#!/usr/bin/perl
use warnings;
use strict;

my %step = (
            'notepadapp' => \&notepadapp,
            'step1' => \&step1,
            'step2' => \&step2,
            'step3' => \&step3,
##          'test'  => \&test,
          );

if ( ! $ARGV[0] ) { print "Please provide the step as the first parameter: answer stepx\n"; return }

foreach my $request ( @ARGV ) {
  if ( ! $step{$request} ) { print "No answer for $request\n" }
  else { &{$step{$request}} }
}

##########################################################################
sub setowner {
  my ($web, $owner ) = @_;
  
  my $command = "chown -R $owner $web";
  
  return `$command`;  
}

##########################################################################
sub refresh {
  my ($web ) = @_;
  
  my $dir = `pwd`;
  
  my $command =
            'cd /var/www/foswiki/bin; '
          . './view ' . $web . '.WebHome -refresh=on;'
          . 'cd ' . $dir;
          
  return `$command`;
}

##########################################################################
sub notepadapp {
  my ( $cmd, @command );
  
  @command = qw(
      tar
           -xvzf /tmp/NotePadApp.tgz
           -C /var/www/foswiki/data/Applications
  );
  $cmd = join( " ", @command ); `$cmd`; 

  setowner( 'Applications', 'nginx:nginx' );
  refresh( 'Applications' );
}

##########################################################################
sub step1 {
  my ( $cmd, @command);
  
  @command = qw(
      tar
           --wildcards
           -xvzf /tmp/SolNotePadApp.tgz
           -C /var/www/foswiki/data/Applications
           --exclude SolNotPadApp/Note*
           SolNotePadApp/* 
    );
    $cmd = join( " ", @command ); `$cmd`;
   
####  NoteForm rev=4
####  NoteType rev=4
####  NoteWebHome rev=2
####  NoteTemplate rev=1
  
  @command = qw(
      pushd bin;
      ./manage Applications/SolNotePadApp/NoteTemplate
           -action restoreRevision
           -rev 1;
      popd
    );
    $cmd = join( " ", @command );
    print $cmd, "\n:;
    `$cmd`;
    
  @command = qw(
      tar2
           --wildcards
           -xvzf /tmp/SolNotePad.tgz
           -C /var/www/foswiki/data/Sandbox
           SolNotePad/Web* 
    );
    $cmd = join( " ", @command ); `$cmd`;
  
  setowner( 'Sandbox', 'nginx:nginx' );
  setowner( 'Applications', 'nginx:nginx' );
  refresh( 'Applications' );
}

##########################################################################
sub step2 {
    my ( $cmd, @command);
  
  @command = qw(
      tar
           --wildcards
           -xvzf /tmp/WorkbenchExample.tgz
           -C /var/www/foswiki/data/Sandbox
           Ex01*
           
    );
  $cmd = join( " ", @command ); `$cmd`; 
#  `tar --wildcards -xvzf /tmp/SolutionExampleTopics.tgz -C /var/www/foswiki/data/Applications SolutionExApp/SolutionExForm*`;
  refresh( 'Sandbox' );
}

##########################################################################
sub step3 {
  my ( $cmd, @command);
  
  @command = qw(
      tar
           --wildcards      
           -xvzf /tmp/WorkbenchExample.tgz
           -C /var/www/foswiki/data/Sandbox
           Ex02* 
    );  $cmd = join( " ", @command ); `$cmd`; 

  refresh( 'Sandbox' );
}

##########################################################################
sub test {
  my @command;
  
    @command = qw(
    tar
        --wildcards
        -xvzf /tmp/SolutionExampleSandbox.tgz
        -C /var/www/foswiki/data/Sandbox
        SolutionExType* SolutionExNote1*
  
);
print join( ' ', @command), "\n";
}
