#!/usr/bin/perl
use warnings;
use strict;

my %step = (
            'notepadapp' => \&notepadapp,
            'step1' => \&step1,
            'step2' => \&step2,
            'step3' => \&step3,
##          'test'  => \&test,
          );

if ( ! $ARGV[0] ) { print "Please provide the step as the first parameter: answer stepx\n"; return }

foreach my $request ( @ARGV ) {
  if ( ! $step{$request} ) { print "No answer for $request\n" }
  else { &{$step{$request}} }
}

##########################################################################
sub restoreRevision {
  my ( $selections ) = @_;

  my $dir = `pwd`;
  chdir( '/var/www/foswiki/bin' );
  while( my ( $webTopic, $rev) = each %{$selections}) {
    system( "./manage $webTopic -action restoreRevision -rev $rev" )
         if ( -e "/var/www/foswiki/data/$webTopic,pfv/" . ($rev+1) );
    print "Restored $webTopic to rev $rev. Result: ", $! ? $! : 'OK', "\n"
  }
  chdir( $dir );

}

##########################################################################
sub refresh {
  my ($web ) = @_;
  
  my $dir = `pwd`;
  
  my $command =
            'cd /var/www/foswiki/bin; '
          . './view ' . $web . '.WebHome -refresh=on;'
          . 'cd ' . $dir;
          
  return `$command`;
}

##########################################################################
sub notepadapp {
  my ( $cmd, @command );
  
  @command = qw(
      tar
           --same-owner
           -xvzf /tmp/NotePadApp.tgz
           -C /var/www/foswiki/data/Applications
  );
  $cmd = join( " ", @command ); `$cmd`; 

  refresh( 'Applications' );
}

##########################################################################
sub step1 {
  my ( $cmd, @command);
  
  @command = qw(
      tar
           --wildcards
           --same-owner
           -xvzf /tmp/SolNotePadApp.tgz
           -C /var/www/foswiki/data/Applications
           SolNotePadApp/* 
    );
    $cmd = join( " ", @command ); `$cmd`;
   
####  NoteForm rev=2
####  NoteType rev=2
####  NoteWebHome rev=2
####  NoteTemplate rev=1
  my %selections = (
                    'Applications/SolNotePadApp/NoteForm' => 2,
                    'Applications/SolNotePadApp/NoteType' => 2,
                    'Applications/SolNotePadApp/NoteWebHome' => 2,
                    'Applications/SolNotePadApp/NoteTemplate' => 1
                    );
  
  restoreRevision( \%selections );
    
  @command = qw(
      tar
           --wildcards
           --same-owner
           -xvzf /tmp/SolNotePad.tgz
           -C /var/www/foswiki/data/Sandbox
           SolNotePad/Web* 
    );
    $cmd = join( " ", @command ); `$cmd`;
  
  refresh( 'Applications' );
}

##########################################################################
sub step2 {
    my ( $cmd, @command);
    
    ### TestSkinNoteViewTemplate rev 7
    
    step1() unless -d '/var/www/foswiki/data/Applications/SolNotePadApp';
    
    my %selections = (
                'Applications/SolNotePadApp/NoteTemplate' => 2,
                'Applications/SolNotePadApp/TestSkinNoteViewTemplate' => 7     
                     );  
      
    restoreRevision( \%selections );
    refresh( 'Applications' 
}

##########################################################################
sub step3 {
  my ( $cmd, @command);
  
  @command = qw(
      tar
           --wildcards      
           -xvzf /tmp/WorkbenchExample.tgz
           -C /var/www/foswiki/data/Sandbox
           Ex02* 
    );  $cmd = join( " ", @command ); `$cmd`; 

  refresh( 'Sandbox' );
}

##########################################################################
sub test {
  my @command;
  
    @command = qw(
    tar
        --wildcards
        -xvzf /tmp/SolutionExampleSandbox.tgz
        -C /var/www/foswiki/data/Sandbox
        SolutionExType* SolutionExNote1*
  
);
print join( ' ', @command), "\n";
}
