GITROOT=/home/bram/devfoswiki/core/working/TutorialPlugin/tutorialmd/katacoda-scenarios
do: add commit push

add:
	cd ${GITROOT}; git add *
    
commit:
	cd ${GITROOT}; git commit -m "updated by BvO" 
    
push:
	cd ${GITROOT}; git push origin master