FROM foswiki-cgi

# Install the PageOptimizerPlugin
RUN cd /var/www/foswiki &&\
    tools/extension_installer PageOptimizerPlugin -r -enable install&&\
    chown -R daemon:daemon pub/System/PageOptimizerPlugin


