#!/usr/bin/perl

unless ( imageExists( 'kcbase' ) ) {
   print " ... building - docker build -t kcbase -f Dockerfile.foswiki.base .\n";
   `docker build -t kcbase -f Dockerfile.foswiki.base .`
}

startImage( $ARGV[0] );

sub startImage {
   my $buildCmd = sprintf( "docker build -t foswiki-%s -f Dockerfile.foswiki.%s .", $_[0], $_[0] );
   print " ... building - $buildCmd\n";
   `$buildCmd`;

       
   `docker stop foswiki` if containerRunning( "foswiki" );
       
   `docker run -d --rm --name foswiki -p 443:443 foswiki-$_[0]`;
}

sub imageExists{
   `docker image ls | grep --perl-regexp "\\b$_[0]\\b"`; 
}

sub containerRunning{
   `docker container ls | grep --perl-regexp "\\b$_[0]\\b"`;
}