#!/usr/bin/perl

unless ( imageExists( 'kcbase' ) ) {
   print " ... building - docker build -t kcbase -f Dockerfile.foswiki.base .\n";
   `docker build -t kcbase -f Dockerfile.foswiki.base .`
}

startImage( $ARGV[0] );

sub startImage {
   my $buildCmd = sprintf( "docker build -t foswiki-%s -f Dockerfile.foswiki.%s .", $_[0], $_[0] );
   print " ... building - $buildCmd\n";
   `$buildCmd`;

       
   `docker stop foswiki` if containerRunning( "foswiki" );
    
    print " ... running - docker run -d --rm --name foswiki -p 443:443 foswiki-$_[0]\n";   
   `docker run -d --rm --name foswiki -p 443:443 foswiki-$_[0]`;

   print_timing();
}

sub print_timing{
   my $command = 'wget -pq --no-check-certificate -O/dev/null http://localhost/foswiki';
   my $timing = '/usr/bin/time --quiet -f "%e" ';
   my $cmd = $timing . $command;
   my $time = qx($cmd 2>&1 1>/dev/null);
   print " ... Response ", 1000 * $time, "ms\n" if $time && $time > 0;
}

sub imageExists{
   `docker image ls | grep --perl-regexp "\\b$_[0]\\b"`; 
}

sub containerRunning{
   `docker container ls | grep --perl-regexp "\\b$_[0]\\b"`;
}