#!/bin/bash
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
sudo apt update
sudo apt install gh

### Install shh key
## ssh-keygen -t ed25519 -C "root@host01"
## eval "$(ssh-agent -s)"
## ssh-add ~/.ssh/id_ed25519
## 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